import re
from typing import Dict, List

QualityAttributesMap = Dict[str, List[str]]


def strip_qa_from_regex(qa):
    qa_without_regex_symbols = re.sub(r'\\b|.\?', '', qa)
    return qa_without_regex_symbols


def qa_sorter(qa: str):
    # Sorts quality attributes by number of words (Highest first), number of hyphens (Highest first),
    # length (Lowest first), and alphabetically (A to Z)
    qa_without_regex_symbols = strip_qa_from_regex(qa)
    return -qa.count(" "), -qa.count("-"), -len(qa_without_regex_symbols), qa_without_regex_symbols


def transform_quality_attributes(qas: QualityAttributesMap, sorter=qa_sorter, *, keep_regex_notation=True):
    return {qa: sorted(keywords if keep_regex_notation else (strip_qa_from_regex(keyword) for keyword in keywords),
                       key=sorter) for qa, keywords in qas.items()}


quality_Attributes_raw = {
    'availability': ['bidirect model transform', 'parallel comput pattern', 'markov transit matrix',
                     'fault toler pattern', 'fault tree analysi', 'save retriev state', 'rate sever failur',
                     'repair rate sever', 'high-avail', 'state-awar', 'checkpoint', 'heartbeat', 'redundan', 'watchdog',
                     'cluster', 'consist', 'downtim', r'haproxy\b', 'mainten', 'monitor', 'unavail', 'backup', 'degrad',
                     'failov', 'failur', 'markov', 'operat', 'reboot', 'reliab', 'repair', 'replic', 'restor', 'robust',
                     'servic', 'standy', 'avail', 'error', 'escal', 'fault', 'incid', 'outag', 'recov', 'state',
                     'stead', 'toler', 'uptim', 'down', 'echo', 'heal', 'mask', r'mtbf\b', r'mttf\b', r'mttr\b', 'ping',
                     r'sla\b', r'sli\b', r'slo\b', r'ha\b'],
    'deployability': ['product environ', 'deliver capab', 'record replay', 'record-and-replay', 'cd-driven',
                      'infrastructur', 'configurat', 'smartfrog', 'toolchain', 'artifact', 'orchestr', 'redundan',
                      'rollback', 'undeploy', 'automat', 'cluster', 'commiss', 'contain', 'continu', 'downtim',
                      'gateway', 'monitor', 'pipelin', 'resourc', 'rollout', 'version', 'canary', 'compos', 'depend',
                      'deploy', 'instal', 'integr', 'loader', 'observ', 'provis', 'releas', 'servic', 'unload',
                      'upgrad', 'audit', 'build', 'manag', 'modul', 'patch', 'probe', 'recov', 'scale', 'stack',
                      'stage', 'toggl', 'updat', 'fail', 'roll', r'a/b\b', 'api', 'log'],
    'energy efficiency': ['measur energ consum', 'reduc energ consum', 'energ efifcienc', 'green softwar',
                          'carbon emiss', 'energ consum', 'resourc usag', 'reduc energ', 'energy-awar', 'energy-rel',
                          'energy-sav', 'low-pow', 'temperatur', 'sustainab', 'frequenc', 'current', 'estimat',
                          'monitor', 'predict', 'resourc', 'schedul', 'standby', 'batter', 'carbon', 'hibern', 'measur',
                          'profil', 'sensor', 'voltag', 'adapt', 'alloc', 'charg', 'clock', 'cloud', 'drain', 'energ',
                          'fault', 'green', 'manag', 'meter', 'model', 'optim', 'power', 'reduc', 'scale', 'therm',
                          'cool', 'core', 'draw', r'dvfs\b', 'heat', 'joul', 'load', r'watts?\b', r'cpus?\b',
                          r'gpus?\b', 'idl', r'pue\b'],
    'integrability': ['component-bas softwar', 'component-bas system', 'built-in contract', 'failur non-atom',
                      'framework compon', 'compon interfac', 'compon integr', 'compon provid', 'contract test',
                      'observ scheme', 'product famil', 'softwar evolv', 'target system', 'compon model', 'integr test',
                      'compon use', 'specication-bas', 'graph-bas', 'non-atom', 'plug-in', 'intermediar', 'encapsulat',
                      'standardiz', 'asynchron', 'middlewar', 'repositor', 'transform', 'abstract', 'complian',
                      'configur', 'contract', 'discover', 'endpoint', 'interfac', 'metacont', 'orchestr', 'protocol',
                      'translat', 'gluewar', 'modular', 'pipelin', 'version', 'broker', 'buffer', 'compon', 'depend',
                      'filter', 'inject', 'integr', 'mediat', 'messag', 'schema', 'servic', 'adapt', 'batch', 'bridg',
                      'coupl', 'event', 'queue', 'state', 'topic', 'rout', 'wrap', 'api', 'pub', 'sub'],
    'interoperability': ['cots-bas system', 'model transform', 'compon base', 'matur model', 'cot compon', 'licens use',
                         'systems-of-system', 'plug-and-play', 'peer-to-p', 'client-serv', 'event-bas',
                         'controlstructur', 'controltopolog', 'architectur', 'interoperab', 'incompatib', 'connector',
                         'coordinat', 'distribut', 'heterogen', 'middlewar', 'repositor', 'transform', 'compatib',
                         'conflict', 'contract', 'cooperat', 'discover', 'interfac', 'mismatch', 'platform', 'protocol',
                         'skeleton', 'standard', 'translat', r'com/ole\b', 'convers', 'exchang', 'gateway', 'interop',
                         'marshal', 'ontolog', 'registr', 'syntact', 'wrapper', 'compon', 'format', 'integr', 'mediat',
                         'messag', 'semant', 'socket', 'specif', 'adapt', 'bridg', r'corba\b', 'share', 'bind', 'plug',
                         'prox', r'soap\b', r'stub\b', 'api', r'cots?\b', r'eai\b', 'idl', r'orb\b', r'rpc\b', 'xml'],
    'modifiability': ['softwar architectur analys', 'chang scenario elicit', 'chang scenario requir',
                      'maintain semant coher', 'scenario requir adapt', 'softwar chang project', 'chang scenario evalu',
                      'enterpris architectur', 'technic infrastructur', 'architectur descript', 'architectur pattern',
                      'architectur analys', 'architectur design', 'architectur tactic', 'candid architectur',
                      'architectur model', 'architectur view', 'qualit attribut', 'scenario elicit', 'softwar mainten',
                      'chang scenario', 'elicit process', 'notat techniqu', 'scenario evalu', 'strength coupl',
                      'system environ', 'analys modifi', 'chang environ', 'chang project', 'impact analys',
                      'softwar chang', 'chang system', 'compon chang', 'design decis', 'requir adapt', 'requir chang',
                      'semant coher', 'system adapt', 'system chang', 'system modif', 'coupl cohes', 'goal analys',
                      'risk assess', 'cost estim', 'view model', 'responsibil', 'polymorph', 'abstract', 'configur',
                      'encapsul', 'interfac', 'maintain', 'refactor', 'scenario', 'concern', 'inherit', 'interop',
                      'paramet', 'version', 'compon', 'compos', 'depend', 'integr', 'interm', 'portab', 'scalab',
                      'servic', 'upgrad', 'variab', 'adapt', 'cohes', 'coupl', 'evolv', 'exten', 'layer', 'modul',
                      'scale', 'bind', 'deco', r'mvc\b', r'pac\b', 'reu', r'soa\b'],
    'performance': ['perform efficien', 'workload perform', 'resourc perform', 'softwar perform', 'applic perform',
                    'comput resourc', 'improv perform', 'perform analys', 'perform metric', 'perform requir',
                    'perform target', 'cloud resourc', 'optim perform', 'perform engin', 'perform evalu',
                    'perform model', 'perform optim', 'execut model', 'perform issu', 'perform test', 'respons time',
                    'critic flow', 'execut time', 'load balanc', 'load test', 'event-driven', 'multi-thread',
                    'under-provis', 'best-cas', 'multiprocessor', 'bottleneck', 'overprovis', 'retransmit',
                    'throughput', 'concurren', 'multiplex', 'datagram', 'deadlock', 'overhead', 'parallel', 'refactor',
                    'workload', 'content', 'network', 'optimiz', 'perform', 'reindex', 'rendezv', 'resourc', 'schedul',
                    'throttl', 'asynch', 'autosc', 'denorm', 'failur', 'latenc', 'profil', 'scalab', 'batch', 'error',
                    'fault', 'memor', 'queue', 'scale', 'synch', 'cach', 'disk', 'load', 'lock', 'time', 'tune',
                    r'cpus?\b', r'gpus?\b', r'i/o\b', 'iops?', r'lqn\b'],
    'reliability': ['cross-cloud network', 'hybrid multicloud', 'disast recover', 'softwar reliab', 'applic migrat',
                    'container app', 'manag environ', 'cloud deploy', 'cloud ident', 'fully manag', 'manag cloud',
                    'servic mesh', 'bare metal', 'manag tool', 'point-in-tim', 'discrete-tim', 'over-provis',
                    'active-act', 'self-heal', 'fail-saf', 'checkpoint', 'nonlinear', 'dependab', 'redundan',
                    'resilien', 'rollback', 'availab', 'downtim', 'ingress', 'mainten', 'monitor', 'poisson', 'toleran',
                    'anomal', 'backup', 'degrad', 'diagno', 'egress', 'failov', r'growth\b', 'integr', 'markov',
                    'reliab', 'repair', 'rerout', 'restor', 'robust', 'stabil', 'alert', 'fault', r'fmeca\b', 'incid',
                    'outag', 'recov', 'uptim', 'fail', r'fmea\b', r'mtbf\b', r'mttd\b', r'mttf\b', r'mttr\b', r'nhpp\b',
                    r'srgm\b', r'doe\b', r'fta\b', r'pra\b', r'rca\b', r'rdt\b', r'rpos?\b', r'rtos?\b', r'sla\b',
                    r'sli\b', r'slo\b', r'sre\b'],
    'safety': ['safety-crit system', 'fail-saf state', 'safety constraint', 'safety standard', 'behavior model',
               'control action', 'primar channel', 'safety pattern', 'softwar safety', 'critic system', 'process model',
               'restrict appl', 'safety analys', 'safety critic', 'safety requir', 'safety tactic', 'system safety',
               'topolog model', 'safety engin', 'gsn diagram', 'process-control', 'single-point', 'high-assur',
               'fail-saf', 'interlock', 'maintain', 'redundan', 'resilien', 'watchdog', 'monitor', 'permiss', 'predict',
               'prevent', 'resourc', 'standby', 'timeout', 'unhandl', 'anomal', 'backup', 'depend', 'detect', 'except',
               'hazard', 'reliab', 'review', 'robust', 'accid', 'alert', 'avail', 'avoid', 'compl', 'error', 'fault',
               'hazop', 'input', 'manag', 'modul', 'patch', 'recov', 'sanit', 'unsaf', 'updat', 'valid', 'isol', 'reme',
               'risk', 'safe', r'stpa\b', 'test', r'gsns?\b', r'hot\b', 'log', r'ssrs?\b', r'tmr\b'],
    'security': ['least privileg', 'incid respons', 'data protect', 'sensit data', 'man-in-the-middl',
                 'defense-in-depth', 'denial-of-servic', 'privacy-preserv', 'customer-manag', 'assume-breach',
                 'cyber-defens', 'data-exfiltr', 'command-lin', 'non-repudi', 'cross-sit', 'role-bas', 'one-tim',
                 'pci-dss', 'confidential', 'authenticat', 'cryptograph', 'guardrail', 'intercept', 'ransomwar',
                 'adversar', 'antiviru', 'authoriz', 'checksum', 'configur', 'devsecop', 'fairplay', 'imperson',
                 'outbound', 'password', 'playbook', 'rollback', 'availab', 'barrier', 'control', 'decrypt', 'disclos',
                 'encrypt', 'exfiltr', 'firewal', 'hardcod', 'legitim', 'network', 'prevent', 'rootkit', 'sandbox',
                 'scanner', 'session', 'validat', 'vmcrypt', 'access', 'assess', 'attack', 'attest', 'certif', 'cookie',
                 'crypto', 'defend', 'detect', 'govern', 'harden', 'inject', 'integr', 'intrus', 'lineag', 'malwar',
                 'obfusc', 'penetr', 'privil', 'retent', 'stolen', 'stride', 'tenant', 'threat', r'trojan\b', 'audit',
                 'compl', 'empow', 'escal', 'expir', 'expos', 'garbl', 'hipaa', 'ident', 'immut', r'ipsec\b', 'misus',
                 'model', 'modif', 'owasp', 'patch', 'phish', 'polic', 'recov', 'revoc', 'revok', 'rotat', 'sanit',
                 'secop', 'secur', 'theft', 'token', 'triag', 'trust', 'updat', 'auth', r'ddos\b', r'gdpr\b', 'hack',
                 'hash', 'lock', 'loss', r'mtls\b', r'nist\b', 'risk', 'sign', 'team', 'worm', r'apt\b', r'cves?\b',
                 r'dns\b', r'idp\b', r'iso\b', r'jwt\b', 'log', r'rsa\b', r'soc\b', r'ssh\b', r'ssl\b', r'vpn\b',
                 r'xss\b'],
    'testability': ['testab transform', 'softwar testab', 'testab analysi', 'testab measure', 'testab softwar',
                    'design testab', 'impact testab', 'improv testab', 'measur testab', 'smell density',
                    'testab factor', 'testab metric', 'testab requir', 'qualit assur', 'testab model', 'testab refer',
                    'testab smell', 'source-to-sourc', 'self-check', 'black-box', 'data-flow', 'hard-wir', 'instrument',
                    'understand', 'flowgraph', 'automat', 'concern', 'context', 'control', 'coverag', 'monitor',
                    'regress', 'resourc', 'assert', 'depend', 'diagno', 'integr', 'modula', 'observ', 'review', 'coupl',
                    'fuzzy', 'simpl', 'simul', 'trace', 'verif', 'emul', 'hook', 'isol', 'mock', 'plan', r'stub\b',
                    'test', 'unit', 'log', 'spy'],
    'usability': ['interfac design', 'boundar object', 'human comput', 'human factor', 'usab pattern', 'computer-human',
                  'context-sensit', 'alert-manag', 'man-machin', 'usage-cent', 'multi-mod', 'mock-up', 'participator',
                  'walkthrough', 'ethnograph', 'storyboard', 'pluralist', 'responsiv', 'document', 'effectiv',
                  'efficien', 'experien', 'feedback', 'interact', 'keystrok', 'progress', 'prototyp', 'shortcut',
                  'workflow', 'aesthet', 'command', 'confirm', 'consist', 'ergonom', 'guidanc', 'indicat', 'navigat',
                  'perform', 'plastic', 'satisfa', 'support', 'behavi', 'cancel', 'clarit', 'cognit', 'cursor',
                  'custom', 'dialog', 'discov', 'gestur', 'intuit', 'latenc', 'likeab', 'person', 'prefer', 'visual',
                  'widget', 'wizard', 'clear', 'close', 'error', 'input', 'learn', 'memor', 'minim', 'resum', 'simpl',
                  'statu', 'guid', 'help', 'hint', 'menu', 'mous', 'paus', 'stop', 'tool', 'undo', 'usab', 'user',
                  'tip', r'ui\b', r'ux\b']}
quality_attributes = transform_quality_attributes(quality_Attributes_raw)
