tactic_descriptions = {"Ping / Echo": "A mechanism to check the presence and responsiveness of a component.",
                       "Monitor": "Continuously observe the system to detect anomalies.",
                       "Heartbeat": "Regular signals sent between components to confirm operation.",
                       "Timestamp": "Use of timestamps to detect delays and failures.",
                       "Sanity Checking": "Perform basic checks to ensure data or processes are within expected parameters.",
                       "Condition Monitoring": "Assess system conditions to predict and detect failures.",
                       "Voting": "Use multiple redundant components to decide correct operation.",
                       "Exception Detection": "Identify and handle exceptional conditions in the system.",
                       "Self-Test": "Components perform internal tests to check functionality.",
                       "Active Redundancy": "Use multiple active components to take over in case of failure.",
                       "Passive Redundancy": "Standby components take over upon failure.",
                       "Spare": "Extra resources are available to replace failed ones.",
                       "Exception Handling": "Mechanism to handle unexpected errors.",
                       "Rollback": "Restore the system to a previous stable state.",
                       "Software Upgrade": "Replace software components without downtime.",
                       "Retry": "Reattempt a failed operation.",
                       "Ignore Faulty Behavior": "Continue operating despite minor faults.",
                       "Degradation": "Reduce functionality but maintain partial operation.",
                       "Reconfiguration": "Adjust system structure dynamically to bypass faults.",
                       "Shadow": "Run a duplicate process in parallel to compare outputs.",
                       "State Resynchronization": "Synchronize state between components after failure.",
                       "Escalating Restart": "Gradually restart components with increasing impact.",
                       "Non-Stop Forwarding": "Maintain data flow even when components fail.",
                       "Removal from Service": "Temporarily remove components to prevent faults.",
                       "Transactions": "Ensure atomicity and consistency in operations.",
                       "Predictive Model": "Use predictive analytics to anticipate failures.",
                       "Exception Prevention": "Design mechanisms to avoid common faults.",
                       "Increase Competence Set": "Improve system adaptability and self-healing capabilities.",
                       "Manage Sampling Rate": "__sample description", "Limit Event Response": "__sample description",
                       "Prioritize Events": "__sample description", "Reduce Overhead": "__sample description",
                       "Bound Execution Times": "__sample description",
                       "Increase Resource Efficiency": "__sample description",
                       "Increase Resources": "__sample description", "Introduce Concurrency": "__sample description",
                       "Maintain Multiple Copies of Computations": "__sample description",
                       "Maintain Multiple Copies of Data": "__sample description",
                       "Bound Queue Sizes": "__sample description", "Schedule Resources": "__sample description"}
