import os
from pathlib import Path

from constants.foldernames import FolderNames

PROJECT_ROOT = Path(__file__).resolve().parent.parent

class AbsDirPath:
    """
    Defines absolute file system paths for key directories within the project.
    All paths are constructed relative to the dynamically determined PROJECT_ROOT.
    """
    # DIRS

    ROOT = PROJECT_ROOT

    DATA = PROJECT_ROOT / "data"
    RESULTS = PROJECT_ROOT / "results"
    DOCS = PROJECT_ROOT / "docs"
    CONFIG = PROJECT_ROOT / "cfg"
    CONSTANTS = PROJECT_ROOT / "constants"
    RESOURCES = PROJECT_ROOT / "resources"
    STAGES = PROJECT_ROOT / "stages"

    TEMP = PROJECT_ROOT / ".tmp"
    CACHE = PROJECT_ROOT / ".cache"
    LOGS = PROJECT_ROOT / ".logs"

    # SUB DIRS
    QUERIES = RESOURCES / "queries"
    ANALYSIS = STAGES / "analysis"
    KEYWORDS_ORIGINAL = DATA / "keywords"
    # KEYWORDS = DATA / "keywords"
    KEYWORDS = DATA / "keywords_2"
    # KEYWORDS = DATA / "keywords_3"
    TACTICS = CONFIG / "tactics"
    # SAMPLES = DATA / "samples"
    SAMPLES = DATA / "samples_2"
    SAMPLES_VERIFIED = SAMPLES / "verified"


    WIKIS = TEMP / "docs"
    SOURCE_CODE = TEMP / "source"

    # ANALYSIS DIRS
    REPO_TOPICS = ANALYSIS / "repo_topics"
    REPOS = ANALYSIS / "repos"
    KEYWORD_ANALYSIS = ANALYSIS / "keywords"

    # KEYWORD DIRS
    KEYWORDS_MATCHING = KEYWORDS / FolderNames.KEYWORDS_MATCHING_DIR
    O_KEYWORDS_MATCHING = KEYWORDS / FolderNames.O_KEYWORDS_MATCHING_DIR # ID optimizations
    O2_KEYWORDS_MATCHING = KEYWORDS / FolderNames.O2_KEYWORDS_MATCHING_DIR # prep for next stage
    S0_NOISE_FILTERING = KEYWORDS / FolderNames.NOISE_FILTERING_DIR
    O_S0_NOISE_FILTERING = KEYWORDS / FolderNames.O_NOISE_FILTERING_DIR # prep for next stage
    S1_QA_RELEVANCE_CHECK = KEYWORDS / FolderNames.QA_RELEVANCE_CHECK_DIR
    O_S1_QA_RELEVANCE_CHECK = KEYWORDS / FolderNames.O_QA_RELEVANCE_CHECK_DIR # prep for next stage
    S2_ARCH_RELEVANCE_CHECK = KEYWORDS / FolderNames.ARCH_RELEVANCE_CHECK_DIR
    O_S2_ARCH_RELEVANCE_CHECK = KEYWORDS / FolderNames.O_ARCH_RELEVANCE_CHECK_DIR # prep for next stage
    S3_TACTIC_EXTRACTION = KEYWORDS / FolderNames.TACTIC_EXTRACTION_DIR

    # PROMPT TUNING KEYWORD DIRS
    KEYWORDS_PT = KEYWORDS / "prompt_tuning" # prompt tuning
    PT_O_KEYWORDS_MATCHING = KEYWORDS_PT / FolderNames.O_KEYWORDS_MATCHING_DIR # ID optimizations
    PT_S0_NOISE_FILTERING = KEYWORDS_PT / FolderNames.NOISE_FILTERING_DIR
    PT_O_S0_NOISE_FILTERING = KEYWORDS_PT / FolderNames.O_NOISE_FILTERING_DIR # prep for next stage
    PT_S1_QA_RELEVANCE_CHECK = KEYWORDS_PT / FolderNames.QA_RELEVANCE_CHECK_DIR
    PT_O_S1_QA_RELEVANCE_CHECK = KEYWORDS_PT / FolderNames.O_QA_RELEVANCE_CHECK_DIR # prep for next stage
    PT_S2_ARCH_RELEVANCE_CHECK = KEYWORDS_PT / FolderNames.ARCH_RELEVANCE_CHECK_DIR
    PT_O_S2_ARCH_RELEVANCE_CHECK = KEYWORDS_PT / FolderNames.O_ARCH_RELEVANCE_CHECK_DIR # prep for next stage
    PT_S3_TACTIC_EXTRACTION = KEYWORDS_PT / FolderNames.TACTIC_EXTRACTION_DIR



    MERGED = KEYWORDS / FolderNames.MERGED_DIR
    O_MERGED = KEYWORDS / FolderNames.O_MERGED_DIR

    O_KEYWORDS_MATCHING_OLD = KEYWORDS_ORIGINAL / FolderNames.O_KEYWORDS_MATCHING_OLD_DIR
    PARAMETER_TUNING_DIR = KEYWORDS_ORIGINAL / FolderNames.PARAMETER_TUNING_DIR
    PARAMETER_TUNING_RES_DIR = KEYWORDS_ORIGINAL / FolderNames.PARAMETER_TUNING_RES_DIR

    # RESULTS DIRS
    RES_KEYWORDS_MATCHING = RESULTS / FolderNames.RES_KEYWORDS_MATCHING_DIR
    RES_S0_NOISE_FILTERING = RESULTS / FolderNames.RES_NOISE_FILTERING_DIR
    RES_S1_QA_RELEVANCE_CHECK = RESULTS / FolderNames.RES_QA_RELEVANCE_CHECK_DIR
    RES_S2_ARCH_RELEVANCE_CHECK = RESULTS / FolderNames.RES_ARCH_RELEVANCE_CHECK_DIR
    RES_S3_TACTIC_EXTRACTION = RESULTS / FolderNames.RES_TACTIC_EXTRACTION_DIR
