from typing import Dict, List

QualityAttributesMap = Dict[str, List[str]]

quality_attributes = {
    "availability": ["avail", "downtime", "outage", "reliab", "fault", "failure", "error", "robust", "toler",
                     "resilien", "recover", "repair", "failover", "fail-safe", "redundant", "mask", "degraded",
                     "mainten", "ping", "echo", "rollback", "checkpoint", "reboot", "alive", "down", "uptime", "MTBF",
                     "MTTR", "MTTF", "MTTD", "SLA", "SLI", "SLO", "switchover", "cluster", "quorum", "watchdog",
                     "monitor", "standby", "state", "snapshot", "incident", "escalation", "rollback", "recovery",
                     "healing", "partition tolerance", "consistency", "replication", "hot swap", "backup", "restore",
                     "unavailability", "service", "disruption", "operation", "high-availability", "HA"],
    "modifiability": ["modul", "deco", "encapsul", "abstract", "separat", "concerns", "interfac", "depend",
                      "inversion", "open/closed", "design pattern", "scenario", "responsibil", "bind", "parameter",
                      "configur", "discovery", "intermed", "reus", "compos", "interop", "integr", "substit",
                      "version", "extension", "swap", "plug-and-play", "microservices", "service", "SOA", "componen",
                      "PAC", "MVC", "maintain", "upgrad", "scal", "portab", "variab", "adapt", "evolv",
                      "extens", "flexibil", "refact", "inheritance", "polymorphism", "coupl", "cohesion", "layer",
                      "plugin"],
    "performance": ["perform", "latency", "throughput", "response time", "miss rate", "load", "scalab", "bottleneck",
                    "tune", "optimiz", "concurren", "multi-thread", "race condition", "queue", "cache", "throttl",
                    "load balanc", "profil", "resource", "parallel", "asynch", "synch", "I/O", "memory",
                    "event-driven", "batch", "refactor", "time", "execution time", "CPU", "GPU", "network", "disk",
                    "data locality", "overhead", "contention", "deadlock", "lock", "schedul", " scaling", "fault",
                    "failure", "error", "workload"],
    "security": ["secur", "attack", "intrusion", "denial-of-service", "confidential", "integrity", "authoriz",
                 "access", "firewall", "interlock", "encrypt", "validat", "sanitiz", "audit", "threat", "expose",
                 "checksum", "hash", "man-in-the-middle", "password", "certificate", "authenticat", "CAPTCHA",
                 "inject", "cross-site", "XSS", "availab", "log", "risk", "manag vulner", "compl", "govern",
                 "ident", "auth", "privil", "session", "phish", "malware", "ransomware", "spyware", "Trojan",
                 "worm", "rootkit", "sandbox", "patch", "policy", "control", "model", "Bell–LaPadula", "Biba",
                 "Clark–Wilson", "Brewer–Nash", "network", "recov", "intrusion", "detect", "preven", "loss", "trust",
                 "secur", "team", "NIST", "ISO 27001", "PCI-DSS", "HIPAA", "SOC 2", "air gap", "APT", "masquerade",
                 "modif", "replay", "sign", "token", "turnstile", "lock", "barrier", "assess", "configur",
                 "updat", "firmware", "certific"],
    "testability": ["test", "sandbox", "assert", "mock", "stub", "log", "resource", "monitor", "benchmark", "spy",
                    "control", "observ", "isolate", "concern", "understand", "automat", "modula", "decoupl",
                    "coupl", "visibil", "simpl", "coverage", "instrument", "unit", "integrat", "diagnos",
                    "trace", "hook", "depend", " fixture", "emulator", "simulation", "end-to-end", "regression",
                    "validat", "verific", "context", "plan", "review", "walkthrough", "inspect"],
    "usability": ["usab", "user", "experien", "UX", "feedback", "undo", "pause", "resume", "progress", "clear",
                  "learn", "responsiv", "simpl", "guid", "intuit", "learn", "memor", "efficiency", "effectiv",
                  "error", "accessib", "consist", "discover", "navigat", "onboarding", "help", "document",
                  "custom", "personal", "satisfa", "cognitive", "minimalism", "clarity", "visual", "workflow",
                  "input", "confirmation", "cancel", "stop", "close", "command", "feedback", "performance", "latency",
                  "adaptabil", "flexibil", "visibil", " support", "walkthrough", "tool", "tips", "hints", "wizards",
                  "shortcut", "responsiv", "prototyp", "UI", "interact", "guidance", "confirm", "dialog",
                  "status", "indicat", "preferences"],
    "energy efficiency": ["energy", "power", "battery", "charge", "drain", "watt", "joule", "green", "sustainab",
                          "meter", "monitor", "reduce", "allocate", "adapt", "schedul", "sensor", "optimization",
                          "modeling", "prediction", "profil", "measur", "estimat", "management", "sleep mode",
                          "hibernate", "standby", "idle", "DVFS", "voltage", "frequency", "scaling", "clock", "CPU",
                          "core", "GPU", "load", "temperature", "therm", "cool", "resource", "allocation", "carbon",
                          "PUE", "TDP", "schedul", "cloud", "data center", " PMIC", "current", "draw", "heat",
                          "fault"],
    "integrability": ["integrat", "interoperab", "interface", "depend", "inject", "wrap", "bridg", "mediat",
                      "adapter", "contract", "protocol", "message", "synchroniz", "pub", "sub", "pub-sub", "service",
                      "rout", "encapsulat", "standardiz", "modular", "configur", "abstract", "intermediary",
                      "translat", "transform", "repository", "orchestr", "endpoint", "event", "asynchronous",
                      "middleware", "point-to-point", "discovery", "plug-in", "filter", "buffer", "data format", "API",
                      "gateway", "coupl", "compo", "version", "complian", "dependency", "contract", "schema",
                      "data mapping", "interoperability", "interfac", "choreogr", "state", "", "batch", "pipeline",
                      "queue", "topic", "broker"],
    "deployability": ["deploy", "release", "update", "install", "rollout", "rollback", "upgrade", "integrat",
                      "continuous", "hotfix", "patch", "pipeline", "configurat", "rolling", "kill switch",
                      "feature toggle", "toggle", "canary", "A/B", "provision", "infrastructure", "orchestr",
                      "automat", "version", "artifact", "build", "staging", "monitor", "observ", "scaling",
                      "modul", "compos", "contain", " downtime", "service", "API", "gateway", "depend",
                      "management", "undeploy", "commission", "probe", "access control", "security group", "audit",
                      "logging", "resource", "stack", "cluster", "load balancing", "fail", "redundan", " recovery"],
    "safety": ["safe", "unsafe", "hazard", "risk", "avoid", "detect", "remediat", "redund", "predict", "timeout",
               "sanity check", "abort", "interlock", "recover", "isol", "fault", "prevention", "detect", "error",
               "exception", "resilience", "robust", "depend", "reliabil", "maintain", "avail", "failover",
               "fallback", "switchover", "authent", "authoriz", "input", "validation", "sanitization", "whitelisting",
               "blacklisting", "permission", "secure coding", "code review", "penetr", "test",
               "vulnerability scanning", "monitor", "aler", "log", "audit trail", "modul", "resource", "manag",
               "deadlock", "starvation", "compl", "patch", "anomaly", "remed", "backup", "standby", "hot", "watchdog",
               "privileg", "review", "vulnera", "updat"],
    "reliability": [ "reliab","fail", "fault", "robust","toleran", "resilien", "recover", "repair","failover", "fail-safe", "redundan", "degrad","mainten", "uptime", "downtime", "outage", "MTBF", "MTTR", "MTTF", "MTTD", "SLA", "SLO", "SLI", "monitor", "watchdog", "heartbeat", "backup", "restore",     "checkpoint", "rollback", "replicat", "consisten", "FRACAS","RCA", "growth","Duane", "AMSAA", "AMPM", "operat profile", "statist usage", "Markov","hazard","PRA", "dependab", "stress test", "load test", "stabil","availab", "survivab", "self-heal", "incident", "diagnos", "prognos", "health check", "alert", "anomaly", "FMEA", "FMECA", "FTA", "wear-out", "obsolescen", "vulnerab", "threat model", "penetration test", "integrity", "security test", "control-flow", "loop test", "data-flow", "transaction-flow", "domain test", "finite-state", "orthogonal array", "optimal release time", "RGT", "RDT", "RQT", "PRAT", "DOE", "Weibull", "confiden bound"]
}
