tactic_to_category_map = {"Ping/Echo": "Detect Faults", "Monitor": "Detect Faults", "Heartbeat": "Detect Faults",
                          "Timestamp": "Detect Faults", "Sanity Checking": "Detect Faults",
                          "Condition Monitoring": "Detect Faults", "Voting": "Detect Faults",
                          "Exception Detection": "Detect Faults", "Self-Test": "Detect Faults",
                          "Active Redundancy": "Recover from Faults_Preparation and Repair",
                          "Passive Redundancy": "Recover from Faults_Preparation and Repair",
                          "Spare": "Recover from Faults_Preparation and Repair",
                          "Exception Handling": "Recover from Faults_Preparation and Repair",
                          "Rollback": "Recover from Faults_Preparation and Repair",
                          "Software Upgrade": "Recover from Faults_Preparation and Repair",
                          "Retry": "Recover from Faults_Preparation and Repair",
                          "Ignore Faulty Behavior": "Recover from Faults_Preparation and Repair",
                          "Degradation": "Recover from Faults_Preparation and Repair",
                          "Reconfiguration": "Recover from Faults_Preparation and Repair",
                          "Shadow": "Recover from Faults_Reintroduction",
                          "State Resynchronization": "Recover from Faults_Reintroduction",
                          "Escalating Restart": "Recover from Faults_Reintroduction",
                          "Non-Stop Forwarding": "Recover from Faults_Reintroduction",
                          "Removal from Service": "Prevent Faults", "Transactions": "Prevent Faults",
                          "Predictive Model": "Prevent Faults", "Exception Prevention": "Prevent Faults",
                          "Increase Competence Set": "Prevent Faults", "Split Module": "Reduce Size of a Module",
                          "Increase Semantic Coherence": "Increase Cohesion",
                          "Encapsulate": "Separate the User Interface", "Use an Intermediary": "Reduce Coupling",
                          "Restrict Dependencies": "Reduce Coupling", "Refactor": "Reduce Coupling",
                          "Abstract Common Services": "Reduce Coupling", "Component Replacement": "Defer Binding",
                          "Compile-time Parameterization": "Defer Binding", "Aspects": "Defer Binding",
                          "Configuration-time Binding": "Defer Binding", "Resource Files": "Defer Binding",
                          "Runtime Registration": "Defer Binding", "Dynamic Lookup": "Defer Binding",
                          "Interpret Parameters": "Defer Binding", "Startup Time Binding": "Defer Binding",
                          "Name Servers": "Defer Binding", "Plug-ins": "Defer Binding",
                          "Publish-Subscribe": "Defer Binding", "Shared Repositories": "Defer Binding",
                          "Polymorphism": "Defer Binding", "Manage Sampling Rate": "Control Resource Demand",
                          "Limit Event Response": "Control Resource Demand",
                          "Prioritize Events": "Control Resource Demand", "Reduce Overhead": "Resource Adaptation",
                          "Bound Execution Times": "Control Resource Demand",
                          "Increase Resource Efficiency": "Control Resource Demand",
                          "Increase Resources": "Manage Resources", "Introduce Concurrency": "Manage Resources",
                          "Maintain Multiple Copies of Computations": "Manage Resources",
                          "Maintain Multiple Copies of Data": "Manage Resources",
                          "Bound Queue Sizes": "Manage Resources", "Schedule Resources": "Manage Resources",
                          "Detect Intrusion": "Detect Attacks", "Detect Service Denial": "Detect Attacks",
                          "Verify Message Integrity": "Detect Attacks", "Detect Message Delay": "Detect Attacks",
                          "Identify Actors": "Resist Attacks", "Authenticate Actors": "Resist Attacks",
                          "Authorize Actors": "Resist Attacks", "Limit Access": "Resist Attacks",
                          "Limit Exposure": "Resist Attacks", "Encrypt Data": "Resist Attacks",
                          "Separate Entities": "Resist Attacks", "Change Default Settings": "Resist Attacks",
                          "Revoke Access": "React to Attacks", "Lock Computer": "React to Attacks",
                          "Inform Actors": "React to Attacks", "Maintain Audit Trail": "Recover from Attacks",
                          "Restore": "Recover from Attacks",
                          "Specialized Interfaces": "Control and Observe System State",
                          "Record/Playback": "Control and Observe System State",
                          "Localize State Storage": "Control and Observe System State",
                          "Abstract Data Sources": "Control and Observe System State",
                          "Sandbox": "Control and Observe System State",
                          "Executable Assertions": "Control and Observe System State",
                          "Limit Structural Complexity": "Limit Complexity", "Limit Nondeterminism": "Limit Complexity",
                          "Increase semantic coherence": "Separate the User Interface",
                          "Co-locate related responsibilities": "Separate the User Interface",
                          "Restrict dependencies": "Separate the User Interface",
                          "Defer binding": "Separate the User Interface", "Cancel": "Support User Initiative",
                          "Undo": "Support User Initiative", "Pause/resume": "Support User Initiative",
                          "Aggregate": "Support User Initiative", "Maintain task models": "Support System Initiative",
                          "Maintain user models": "Support System Initiative",
                          "Maintain system models": "Support System Initiative", "Metering": "Resource Monitoring",
                          "Static Classification": "Resource Monitoring",
                          "Dynamic Classification": "Resource Monitoring", "Vertical Scaling": "Resource Allocation",
                          "Horizontal Scaling": "Resource Allocation", "Scheduling": "Resource Allocation",
                          "Brokering": "Resource Allocation", "Service Adaptation": "Resource Adaptation",
                          "Increase Efficiency": "Resource Adaptation", "Discover Service": "Locate",
                          "Orchestrate": "Manage Interfaces", "Tailor Interface": "Manage Interfaces"}
