name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use your desired Python version

      # Step 3: Install Python dependencies (if needed)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
#          pip install -r requirements.txt  # Add a requirements.txt if your script has dependencies

      # Step 4: Run the Python script
      - name: Generate resource map
        run: python generate_resource_map.py

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Adjust to the directory where your static site is located